#!/usr/bin/env python3
"""Build the homepage/study CSS bundles with their original cascade order.

Run from any directory with Python 3; --check validates committed output.
Only the standard library is needed. See scripts/README.md.
"""
import argparse
import hashlib
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
BUNDLES = {
    "home-bundle.css": ("index.html", [
        "fonts.css", "styles.css", "refresh.css", "premium.css",
        "study-film.css", "analytics-consent.css", "newsletter.css",
    ]),
    "study-bundle.css": ("magnesium-formulation-study.html", [
        "fonts.css", "styles.css", "refresh.css", "study-experience.css",
        "study-film.css", "research-navigation.css", "analytics-consent.css",
    ]),
}


def build(check=False):
    stale = []
    for output, (page, sources) in BUNDLES.items():
        content = "/* Generated by scripts/build_styles.py. Edit the source CSS files. */\n"
        for source in sources:
            content += f"\n/* Source: {source} */\n" + (ROOT / source).read_text().rstrip() + "\n"
        version = hashlib.sha256(content.encode()).hexdigest()[:12]
        html = (ROOT / page).read_text()
        pattern = rf'<link rel="stylesheet" href="{re.escape(output)}\?v=[a-z0-9-]+">'
        updated, count = re.subn(pattern, f'<link rel="stylesheet" href="{output}?v={version}">', html)
        if count != 1:
            raise ValueError(f"Expected one {output} link in {page}; found {count}")
        if not (ROOT / output).exists() or (ROOT / output).read_text() != content or updated != html:
            stale.append(output)
        if not check:
            (ROOT / output).write_text(content)
            (ROOT / page).write_text(updated)
    if check and stale:
        raise SystemExit("Stale bundles: " + ", ".join(stale) + ". Run python3 scripts/build_styles.py")
    print("CSS bundles are current." if check else "Built homepage and study CSS bundles.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    build(parser.parse_args().check)
